#services:
#    acme.demo.controller:
#        class: oxcom\phpbb-code-highlight\controller\main
#        arguments:
#            - '@config'
#            - '@controller.helper'
#            - '@template'
#            - '@user'

services:
    oxcom.phpbbch.listener:
        class: oxcom\phpbbch\event\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
