services:
    oxcom.phpbbch.listener:
        class: oxcom\phpbbch\event\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
